/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: uadata.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "uadata.pb-c.h"
void   ios_work_query__init
                     (IosWorkQuery         *message)
{
  static IosWorkQuery init_value = IOS_WORK_QUERY__INIT;
  *message = init_value;
}
size_t ios_work_query__get_packed_size
                     (const IosWorkQuery *message)
{
  assert(message->base.descriptor == &ios_work_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ios_work_query__pack
                     (const IosWorkQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ios_work_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ios_work_query__pack_to_buffer
                     (const IosWorkQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ios_work_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IosWorkQuery *
       ios_work_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IosWorkQuery *)
     protobuf_c_message_unpack (&ios_work_query__descriptor,
                                allocator, len, data);
}
void   ios_work_query__free_unpacked
                     (IosWorkQuery *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ios_work_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ua_item__init
                     (UaItem         *message)
{
  static UaItem init_value = UA_ITEM__INIT;
  *message = init_value;
}
size_t ua_item__get_packed_size
                     (const UaItem *message)
{
  assert(message->base.descriptor == &ua_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ua_item__pack
                     (const UaItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ua_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ua_item__pack_to_buffer
                     (const UaItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ua_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UaItem *
       ua_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UaItem *)
     protobuf_c_message_unpack (&ua_item__descriptor,
                                allocator, len, data);
}
void   ua_item__free_unpacked
                     (UaItem *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ua_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ios_work_item__init
                     (IosWorkItem         *message)
{
  static IosWorkItem init_value = IOS_WORK_ITEM__INIT;
  *message = init_value;
}
size_t ios_work_item__get_packed_size
                     (const IosWorkItem *message)
{
  assert(message->base.descriptor == &ios_work_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ios_work_item__pack
                     (const IosWorkItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ios_work_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ios_work_item__pack_to_buffer
                     (const IosWorkItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ios_work_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IosWorkItem *
       ios_work_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IosWorkItem *)
     protobuf_c_message_unpack (&ios_work_item__descriptor,
                                allocator, len, data);
}
void   ios_work_item__free_unpacked
                     (IosWorkItem *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ios_work_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ios_work_query__field_descriptors[5] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IosWorkQuery, userid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IosWorkQuery, url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "headers",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IosWorkQuery, headers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clientMac",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IosWorkQuery, clientmac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IosWorkQuery, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ios_work_query__field_indices_by_name[] = {
  4,   /* field[4] = channel */
  3,   /* field[3] = clientMac */
  2,   /* field[2] = headers */
  1,   /* field[1] = url */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange ios_work_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ios_work_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IosWorkQuery",
  "IosWorkQuery",
  "IosWorkQuery",
  "",
  sizeof(IosWorkQuery),
  5,
  ios_work_query__field_descriptors,
  ios_work_query__field_indices_by_name,
  1,  ios_work_query__number_ranges,
  (ProtobufCMessageInit) ios_work_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ua_item__field_descriptors[1] =
{
  {
    "Headers",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(UaItem, n_headers),
    offsetof(UaItem, headers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ua_item__field_indices_by_name[] = {
  0,   /* field[0] = Headers */
};
static const ProtobufCIntRange ua_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ua_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UaItem",
  "UaItem",
  "UaItem",
  "",
  sizeof(UaItem),
  1,
  ua_item__field_descriptors,
  ua_item__field_indices_by_name,
  1,  ua_item__number_ranges,
  (ProtobufCMessageInit) ua_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ios_work_item__field_descriptors[3] =
{
  {
    "WorkUrl",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IosWorkItem, workurl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Guid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IosWorkItem, guid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "UaList",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(IosWorkItem, n_ualist),
    offsetof(IosWorkItem, ualist),
    &ua_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ios_work_item__field_indices_by_name[] = {
  1,   /* field[1] = Guid */
  2,   /* field[2] = UaList */
  0,   /* field[0] = WorkUrl */
};
static const ProtobufCIntRange ios_work_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ios_work_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IosWorkItem",
  "IosWorkItem",
  "IosWorkItem",
  "",
  sizeof(IosWorkItem),
  3,
  ios_work_item__field_descriptors,
  ios_work_item__field_indices_by_name,
  1,  ios_work_item__number_ranges,
  (ProtobufCMessageInit) ios_work_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
